services:
  app:
    build: . 
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017/observations
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
